import gpt_extract_pipe as ge
import os

if __name__ == '__main__':
    
    # text = "CQDs were synthesized by the usage of O. basilicum L. extract via a simple hydrothermal method (Fig. 1). In a typical one-step synthesizing procedure, 2.0 g of O. basilicum L. seed was added to 100 mL of distilled water and stirred at 50 °C for 2 h. Then, the obtained extract was filtered and transferred into a 100 mL Teflon-lined stainless-steel autoclave to be heated at 180 °C for 4 h. Once the autoclave was cooled naturally at room temperature and the solution was centrifuged (12,000 rpm) for 15 min, the prepared brown solution was filtered through a fine-grained 0.45 μm membrane to remove larger particles. Finally, the solution was freeze-dried to attain the dark brown powder of CQDs."
    # text_2 ='S-doped C-dots were synthesized using a hydrothermal method. Briefly, 25 mL sodium citrate solution (0.1 M) and sodium thiosulfate were added into a 50 mL Teflon-lined stainless steel autoclave. After that, the autoclave was kept at a fixed temperature (160, 180, 200, 220 or 240 °C) for 6 h. The product could be used after filtration with a cylinder filtration membrane filter (0.22 μm).'
    text = "Meanwhile, the Si-CQDs have a high QY of 34.8% compared with the reference of 0.1 mol/L quinine sulfate (Fig. S4). It is important that the as-prepared Si-CQDs exhibit up-conversion PL properties. We know that the photon avalanche, excited state absorption and energy transfer up-conversion are three basic mechanisms to explain up-conversion fluorescence. However, up-conversion PL derives from more than one fundamental mechanism in most cases. There have different reviews concerning the explanation for the up-conversion fluorescence of CQDs. Among them, the multi-photon active process, in which the simultaneous absorption of two or more photons, is the common explanation for up-conversion fluorescence of CQDs [1,50,51]. As shown in Fig. 3d, the Si-CQDs were excited at 700 to 800 nm wavelength. The up-conversion fluorescence spectra show the fixed emission peaks at 452 nm, indicating that the fluorescence emission occurs from the lowest singlet state regardless of the excitation wavelength [52]. Unlike conventional PL imaging, the up-conversion PL not only offers lower self-fluorescence photodamage and photo-toxicity, but also allows deeper light penetration and reduced light scattering for the anti-stokes emission during excitation in the NIR range."
    text_2 = "In order to study the effect of solvent on the photoluminescence behavior of CDs, H2O (WAT), MeOH (MET), EtOH, Me2CO (ACE), tetrahydrofuran (THF), and N,N -dimethylformamide (DMF) were chosen as solvents to measure the PLQYs of CDs in different solvents. A series of dilute solutions with different concentrations were prepared for each CDs, and their fluorescence spectra and UV–Vis absorption spectra were acquired. The integrated fluorescence intensity was plotted against the UV–vis absorbance, as shown in Fig. 5 a–c. One can estimate the PLQY of CDs using quinine sulfate as the reference. Fig. 5d–f displays the PLQY for the three CDs in different solvents. The PLQY of B-CDs in different solvents is21.3% (H2O), 23.7% (MeOH), 23.0% (EtOH), 23.2% (Me2CO), 5.76% (THF), 28.9% (DMF) respectively. The PLQY of G-CDs in different solvents is 6.32% (H2O), 21.5% (MeOH), 28.3% (EtOH), 33.8% (Me2CO), 30.9% (THF), 31.4% (DMF) respectively. One can see that B-CDs and G-CDs exhibit fully different luminescence performance in different solvents. B-CDs have the highest PLQY in DMF and the lowest one in THF while G-CDs have the highest PLQY in Me2CO and the lowest one in H2O. Similar to G-CDs, R-CDs show highest PLQY in Me2CO, reaching 12.3% while the lowest one in H2O, only 2.07%. From the above results, although B-CDs were synthesized using DMF as solvent, the PLQY only has slight decrease in water. In contrast, both G-CDs and R-CDs were synthesized with ethanol as solvent, and their PLQY decreased seriously in water."
    text_3 = "In this way, the characterizations performed in this work enabled the evaluation of how the composition of GQDs and their most important functional groups contribute to their luminescent behavior. For instance, the ─OH group contributes to a higher QY as their emissions are at the blue region, while the ─COOH groups are also important for luminescence, but their emission occurs at longer λ, which can lead to a decrease in the QY value."
    text_4 = "The quantum yields (QY) of the Tg N,P-CDs was determined to be 9.44% (Q R = 0.54, I R = 671.536, I CDs = 301.749, A CDs = 0.036, A R = 0.014) based on standard quinine sulfate (QY = 54%), while that of Tg CDs (only Thelephora ganbajun Zang as material) was 7.25% (Q R = 0.54, I R = 671.536, I CDs = 90.129, A CDs = 0.014, A R = 0.014)."
    result = ge.gpt_extract_QY(text_4)
    print(result)
    # print(len(result))
    # file_dir = '/home/ptoka/para_30_sample.txt'
    # save_dir = '/home/ptoka/gpt_synth_30_sample.json'
    # result = ge.gpt_extract_synth(file_dir, save_dir)